### PR TITLE
Update acolytefight.d.ts

### PR DESCRIPTION
**Pull request by justchen1369**
RaR is hijacking his brother's account

### CODE REVIEW

**Comment by notrealn** [comment]
but it cant?
image
this will just make the bot think there are less/more than 60 ticks in a second. it wont actually affect the game

**Comment by notrealn** [comment]
in fact, if you completely remove it (and its references) **nothing happens**

**Comment by notrealn** [comment]
please close PR?

**Comment by justchen1369** [comment]
> but it cant?
> image
> this will just make the bot think there are less/more than 60 ticks in a second. it wont actually affect the game

hmm, interesting

**Pull request closed without merging**
